### ISSUE TITLE
Script PATH problem

### ISSUE THREAD

**Issue by LaironSk** [HenriqueBBrum/DINT#10]
Inside the script it seems that the path is configured as "~/Documents/DIDNT/testing/results", which means that your DINT should always be inside a Documents folder. Please inform that on the README.md or change the script otherwise.

**Comment by HenriqueBBrum** [comment]
Hi, this is already documented in the main README.md. It is on the paragraph right below the "Installation Guide" header. Currently it can sound like a suggestion so I will update the text to remove this vagueness.
